language: python

python:
  - "3.6"

service:
  - postgresql

install:
  - cd service-analytics && pip install -r requirements.txt

before_script:
  - export APP_SETTINGS="project.config.TestingConfig"
  - export DATABASE_TEST_URL=postgresql://postgres:@localhost/users_test
  - psql -c 'create database users_test;' -U postgres
  - cd service-analytics && python manage.py recreate_db

script:
  - cd service-analytics && python manage.py test