version: '3.3'

services:
  database:
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == node-2]
      restart_policy:
        condition: on-failure
    image: omdv/crypto-database:latest
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: exit 0
    networks:
      - cryptosite

  analytics:
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
    image: omdv/crypto-analytics:latest
    environment:
      - APP_SETTINGS=project.config.ProductionConfig
      - DATABASE_URL=postgres://postgres:postgres@database:5432/analytics_prod
      - DATABASE_TEST_URL=postgres://postgres:postgres@database:5432/analytics_test
      - SECRET_KEY=${SECRET_KEY}
      - GIT_TOKEN=${GIT_TOKEN}
      - GIT_USER=${GIT_USER}
    depends_on:
      - database
      - redis
    networks:
      - cryptosite

  client:
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == node-3]
      restart_policy:
        condition: on-failure
    image: omdv/crypto-client:latest
    environment:
      - NODE_ENV=production
      - REACT_APP_GIT_SERVICE_URL=${REACT_APP_GIT_SERVICE_URL}
    depends_on:
      - analytics
    networks:
      - cryptosite

  nginx:
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == node-4]
      restart_policy:
        condition: on-failure
    image: omdv/crypto-nginx:latest
    ports:
      - 80:80
    depends_on:
      - analytics
      - client
    networks:
      - cryptosite

  redis:
    image: redis:alpine
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
    networks:
      - cryptosite

networks:
  cryptosite:

volumes:
  db-data: