version: '3.1'

services:

  database:
    container_name: database
    build:
      context: ./service-db
      dockerfile: Dockerfile
    ports:
        - 5435:5432  # expose ports - HOST:CONTAINER
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: exit 0

  analytics:
    container_name: analytics
    build:
      context: ./service-analytics/
      dockerfile: Dockerfile-prod
    volumes:
      - './service-analytics:/usr/src/app'
    ports:
      - 5000
    environment:
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@database:5432/analytics_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@database:5432/analytics_test
      - SECRET_KEY=my_long_secure_key
    depends_on:
      - database
    links:
      - database
    secrets:
     - my_git_secret

  client:
    container_name: client
    build: ./service-client
    ports:
      - '3007:3000' # expose ports - HOST:CONTAINER
    environment:
      - NODE_ENV=production
      - GIT_SERVICE_URL=http://127.0.0.1
    depends_on:
      - analytics
    links:
      - analytics

  nginx:
    container_name: nginx
    build: ./nginx/
    restart: always
    ports:
      - 80:80
    depends_on:
      - analytics
    links:
      - analytics

secrets:
  my_git_secret:
    file: ./gitsecret.key