version: '2.1'

services:

  database:
    container_name: database
    build: ./service-db
    ports:
        - 5435:5432  # expose ports - HOST:CONTAINER
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: exit 0

  analytics:
    container_name: analytics
    build: ./service-analytics/
    volumes:
      - './service-analytics:/usr/src/app'
    ports:
      - 5001:5000 # expose ports - HOST:CONTAINER
    environment:
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@database:5432/analytics_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@database:5432/analytics_test
      - SECRET_KEY=my_long_secure_key
    depends_on:
      database:
        condition: service_healthy
    links:
      - database

  poller:
    container_name: poller
    build: ./service-gitpoll/
    volumes:
      - './service-gitpoll:/usr/src/app'
    ports:
      - 5002:5000 # expose ports - HOST:CONTAINER
    environment:
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@database:5432/analytics_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@database:5432/analytics_test
      - SECRET_KEY=my_long_secure_key
    depends_on:
      database:
        condition: service_healthy
    links:
      - database