FROM node:alpine

# set working directory and copy app
WORKDIR /usr/src/app
COPY . /usr/src/app/

# arguments
ARG REACT_APP_GIT_SERVICE_URL
ENV REACT_APP_GIT_SERVICE_URL $REACT_APP_GIT_SERVICE_URL
ARG NODE_ENV
ENV NODE_ENV $NODE_ENV

# install and build
RUN set -ex; \
  yarn install --frozen-lockfile --production --no-cache; \
  yarn run build

# serve as static page
FROM nginx:1.13.5-alpine
WORKDIR /usr/share/nginx/html
COPY --from=0 /usr/src/app/build/ /usr/share/nginx/html