FROM node:latest

# set working directory
RUN mkdir /usr/src/app
WORKDIR /usr/src/app

# arguments
ARG REACT_APP_GIT_SERVICE_URL
ARG NODE_ENV
ENV NODE_ENV $NODE_ENV
ENV REACT_APP_GIT_SERVICE_URL $REACT_APP_GIT_SERVICE_URL

# add `/usr/src/app/node_modules/.bin` to $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH

# add app
# ADD . /usr/src/app

# install and cache app dependencies
#ADD package.json /usr/src/app/package.json
#RUN npm install --silent
#RUN npm install react-scripts@1.0.15 -g --silent

RUN yarn install

# start app
CMD ["npm", "start"]