kind: Service
apiVersion: v1
metadata:
  name: "{{.Values.flask.name}}"
  labels:
    name: "{{.Values.flask.name}}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
spec:
  type: "{{.Values.flask.service.serviceType}}"
  ports:
  - protocol: TCP
    port: {{.Values.flask.container.port}}
    targetPort: {{.Values.flask.container.port}}
  selector:
    app: "{{.Values.flask.name}}"